"""Add vegetarian_friendly_score to Item and Restaurant

Revision ID: b28149da8a3e
Revises: 
Create Date: 2023-04-22 22:51:30.692921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b28149da8a3e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('vegetarian_friendly_score', sa.Float(), nullable=True))
    op.add_column('restaurant', sa.Column('vegetarian_friendly_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurant', 'vegetarian_friendly_score')
    op.drop_column('item', 'vegetarian_friendly_score')
    # ### end Alembic commands ###
